# Generated by Django 3.0.6 on 2020-06-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20200610_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(choices=[('Sun, Jun 14', 'Sun, Jun 14'), ('Mon, Jun 15', 'Mon, Jun 15'), ('Tue, Jun 16', 'Tue, Jun 16'), ('Wed, Jun 17', 'Wed, Jun 17'), ('Thu, Jun 18', 'Thu, Jun 18'), ('Fri, Jun 19', 'Fri, Jun 19'), ('Sat, Jun 20', 'Sat, Jun 20')], max_length=20),
        ),
    ]
