# Generated by Django 3.0.6 on 2020-06-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='short_description',
        ),
    ]
